import streamlit as st

st.set_page_config(
    page_title="Schedule Explorer",
    page_icon="📅",
    layout="wide",
)

st.write("# Welcome to Schedule Explorer! 👋")

st.sidebar.success("Select a policy above.")

st.markdown(
    """
    Schedule Explorer is an interactive tool for visualizing and
    analyzing schedules generated by the Scheduler Library. Note
    that the schedules generated in this tool **does not affect** 
    the actual schedule pulled by the telescope. The commands are
    to be copied and pasted into nextline to be executed.
"""
)